app/routes/collections.py
# routes/collections.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from app import db
from models import Collection, CollectionBookAssociation, Book

bp = Blueprint('collection', __name__, url_prefix='/collection')

@bp.route('/my_collections', methods=['GET'])
@login_required
def my_collections():
    collections = Collection.query.filter_by(user_id=current_user.id).all()
    return render_template('collections/collections.html', collections=collections)

@bp.route('/collection/<int:collection_id>', methods=['GET'])
@login_required
def view_collection(collection_id):
    collection = Collection.query.get_or_404(collection_id)
    
    # Проверяем, что текущий пользователь имеет доступ к просмотру коллекции
    if collection.user_id != current_user.id:
        abort(403)
    
    books = collection.books  # collection.books уже представляет список книг
    
    return render_template('collections/view_collection.html', collection=collection, books=books)

@bp.route('/add_collection', methods=['POST'])
@login_required
def add_collection():
    name = request.form.get('name')
    if name:
        new_collection = Collection(name=name, user_id=current_user.id)
        db.session.add(new_collection)
        db.session.commit()
        flash(f'Подборка успешно добавлена!', 'success')
    else:
        flash(f'Название подборки не может быть пустым!', 'danger')
    return redirect(url_for('collection.my_collections'))

@bp.route('/add_to_collection', methods=['POST'])
@login_required
def add_to_collection():
    collection_id = request.form.get('collection_id')
    book_id = request.form.get('book_id')
    collection = Collection.query.get_or_404(collection_id)
    book = Book.query.get_or_404(book_id)

    if collection.user_id != current_user.id:
        abort(403)
    
    # Проверка, что книга не добавлена в коллекцию ранее
    existing_association = CollectionBookAssociation.query.filter_by(collection_id=collection_id, book_id=book_id).first()
    if not existing_association:
        association = CollectionBookAssociation(collection_id=collection.id, book_id=book.id)
        db.session.add(association)
        db.session.commit()
        flash(f'Книга успешно добавлена в подборку!', 'success')
    else:
        flash(f'Книга уже была добавлена в подборку!', 'primary')

    return redirect(url_for('book.show', book_id=book.id))

@bp.route('/delete_collection/<int:collection_id>', methods=['POST'])
@login_required
def delete_collection(collection_id):
    collection = Collection.query.get_or_404(collection_id)

    # Проверяем, что текущий пользователь имеет доступ к удалению коллекции
    if collection.user_id != current_user.id:
        abort(403)

    try:
        # Удаляем все ассоциации книг с этой коллекцией
        CollectionBookAssociation.query.filter_by(collection_id=collection_id).delete()
        
        # Удаляем саму коллекцию
        db.session.delete(collection)
        db.session.commit()

        flash(f'Подборка успешно удалена!', 'success')
    except Exception as e:
        flash(f'Ошибка при удалении подборки: {str(e)}', 'danger')
        db.session.rollback()

    return redirect(url_for('collection.my_collections'))

app/templates/book/edit.html
{% extends 'base.html' %}
{% from 'book/form.html' import render_book_form %}

{% block content %}
<div class="container">
    
    <h2 class="my-3 text-center text-uppercase font-weight-bold">Редактирование книги</h2>
    
    {{ render_book_form(url_for('book.edit', book_id=book.id), genres, book, selected_genres_list) }}
    
</div>
{% endblock %}

app/templates/book/form.html
{% macro render_book_form(url, genres, book={}, selected_genres_list=[]) %}
<form action="{{ url }}" method="POST" enctype="multipart/form-data">
    <div class="mb-3 row">
        <div class="col-md-12 d-flex flex-column">
            <div class="mb-3">
                <label for="title">Название книги</label>
                <input class="form-control" type="text" name="title" id="title" value="{{ book.title or '' }}">
            </div>
            <div class="mb-3">
                <label for="genre">Жанры</label>
                <select multiple class="form-select" name="genre_id" id="genre">
                    <option value="0">Не выбрано</option>
                    {% for genre in genres %}
                    <option value="{{ genre.id }}" {% if genre.id in selected_genres_list %}selected{% endif %}>{{
                        genre.genre_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="author">Автор</label>
                <input class="form-control" type="text" name="author" id="author" value="{{ book.author or '' }}">
            </div>
            <div class="mb-3">
                <label for="publisher">Издательство</label>
                <input class="form-control" type="text" name="publisher" id="publisher"
                    value="{{ book.publisher or '' }}">
            </div>
            <div class="mb-3">
                <label for="amount">Количество страниц</label>
                <input class="form-control" name="amount" type="number" id="amount" value="{{ book.amount or '500' }}">
            </div>
            <div class="mb-3">
                <label for="year">Год издания</label>
                <input class="form-control" type="number" min="1900" max="2070" step="1"
                    value="{{ book.year or '2023' }}" name="year" id="year">
            </div>
            <div class="mb-3 d-flex flex-column flex-grow-1">
                <label for="inputDesc">Описание книги</label>
                <textarea type="text" class="form-control flex-grow-1" name="description" id="inputDesc"
                    value="{{ book.description or '' }}">{{ book.description or '' }}</textarea>
            </div>
        </div>
        {% if request.endpoint in ['book.new'] %}
        <div class="col-md-12 d-flex flex-column">
            <div class="mb-3">
                <label for="cover_img">Обложка</label>
                <input class="form-control" type="file" name="cover_img" id="cover_img">
            </div>
            <div class="mb-3 background-preview p-3 rounded d-flex align-items-center justify-content-center">
                <img src="#" class="img-fluid d-none" alt="">
                <label for="cover_img" class="btn btn-dark">Выбрать обложку</label>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="mb-3 text-center">
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
</form>
<script src="{{ url_for('static', filename='easyMDE.js')}}"></script>
{% endmacro %}

app/templates/book/new.html
{% extends 'base.html' %}
{% from 'book/form.html' import render_book_form %}

{% block content %}
<div class="container">
    
    <h2 class="my-3 text-center text-uppercase font-weight-bold">Добавление новой книги</h2>
    
    {{ render_book_form(url_for('book.new'), genres) }}
    
</div>
{% endblock %}

app/templates/book/review.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <h2 class="my-3 text-center text-uppercase font-weight-bold">Написание рецензии "{{ book.title }}"</h2>

    <form method="POST">
        <div class="mb-3 d-flex flex-column flex-grow-1">
            <label for="review">Напишите отзыв</label>
            <textarea class="form-control flex-grow-1" name="review" id="review" cols="30" rows="5"></textarea>
            <script>
                const easyMDE = new EasyMDE();
            </script>
        </div>
        <div class="mb-3 form-group">
            <label for="exampleFormControlSelect1">Ваша оценка</label>
            <select class="form-control" id="exampleFormControlSelect1" name="mark">
                <option value="5">Отлично</option>
                <option value="4">Хорошо</option>
                <option value="3">Удовлетворительно</option>
                <option value="2">Неудовлетворительно</option>
                <option value="1">Плохо</option>
                <option value="0">Ужасно</option>
            </select>
        </div>
        <div class="mb-3 text-center">
            <input type="submit" class="btn btn-primary" value="Сохранить отзыв">
        </div>
    </form>
</div>

{% endblock %}

app/templates/book/show.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">

    <h2 class="my-3 text-center text-uppercase font-weight-bold">Просмотр книги</h2>

    <table class="table">
        <tbody>
            <tr>
                <td>Название книги</td>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <td>Жанры</td>
                <td>
                    {% for genre in book_genre %}
                    {% if genre.books_id == book.id %}{{ genre.genre.genre_name }}</br>{% endif %}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>Автор</td>
                <td>{{ book.author }}</td>
            </tr>
            <tr>
                <td>Издательство</td>
                <td>{{ book.publisher }}</td>
            </tr>
            <tr>
                <td>Описание книги</td>
                <td>{{ book.description | safe }}</td>
            </tr>
        </tbody>
    </table>
    <div class="col-md-3 mb-3 mb-md-0 d-flex align-items-center justify-content-center">
        <div class="course-logo" style="background-image: url({{ img }});">
        </div>
    </div>
    <br><br>

    {% if reviews %}
    <div class="reviews">
        <h3>Рецензии пользователей</h3>
        {% for review in reviews %}
            <div class="d-flex flex-column mt-2">
                <hr>
                <div class="d-flex">
                    <div class="flex-grow-1 ms-3 col-10">
                        <h5>{{ review.get_user() }}: Оценка {{ review.rating }}</h5>
                        <p><span>{{ review.text | safe }}</span></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}


    {% if current_user.is_authenticated and not review %}
    <div class="text-center my-3">
        <a class="btn btn-lg btn-primary" href="{{ url_for('book.review', book_id=book.id) }}">Написать рецензию</a>
    </div>
    {% endif %}

    {% if reviews %}
    {% for review in reviews %}
    
    {% if review.status == True%}
    <div class="d-flex flex-column mt-2 border">
        <div class="d-flex">
            <div class="flex-grow-1 ms-3">
                <h5>{{ review.get_user() }}: Оценка {{ review.rating }} </h5>
                <p><span>{{ review.text | safe }}</span></p>
            </div>
        </div>
    </div>

    {% endif %}
    {% endfor %}
    {% endif %}

    {% if current_user.is_authenticated %}
    <!-- Add to Collection Button -->
    <div class="text-center my-3">
        <button type="button" class="btn btn-lg btn-secondary" data-toggle="modal" data-target="#addToCollectionModal">Добавить в подборку</button>
    </div>
    {% endif %}
</div>

<!-- Add to Collection Modal -->
<div class="modal fade" id="addToCollectionModal" tabindex="-1" role="dialog" aria-labelledby="addToCollectionModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="POST" action="{{ url_for('collection.add_to_collection') }}">
                <div class="modal-header">
                    <h5 class="modal-title" id="addToCollectionModalLabel">Добавить в подборку</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="book_id" value="{{ book.id }}">
                    <div class="form-group">
                        <label for="collection">Выберите подборку:</label>
                        <select class="form-control" id="collection" name="collection_id">
                            {% for collection in current_user.collections %}
                            <option value="{{ collection.id }}">{{ collection.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}