app/routes/collections.py
# routes/collections.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from app import db
from models import Collection, CollectionBookAssociation, Book

bp = Blueprint('collection', __name__, url_prefix='/collection')

@bp.route('/my_collections', methods=['GET'])
@login_required
def my_collections():
    collections = Collection.query.filter_by(user_id=current_user.id).all()
    return render_template('collections/collections.html', collections=collections)

@bp.route('/collection/<int:collection_id>', methods=['GET'])
@login_required
def view_collection(collection_id):
    collection = Collection.query.get_or_404(collection_id)
    
    # Проверяем, что текущий пользователь имеет доступ к просмотру коллекции
    if collection.user_id != current_user.id:
        abort(403)
    
    books = collection.books  # collection.books уже представляет список книг
    
    return render_template('collections/view_collection.html', collection=collection, books=books)

@bp.route('/add_collection', methods=['POST'])
@login_required
def add_collection():
    name = request.form.get('name')
    if name:
        new_collection = Collection(name=name, user_id=current_user.id)
        db.session.add(new_collection)
        db.session.commit()
        flash(f'Подборка успешно добавлена!', 'success')
    else:
        flash(f'Название подборки не может быть пустым!', 'danger')
    return redirect(url_for('collection.my_collections'))

@bp.route('/add_to_collection', methods=['POST'])
@login_required
def add_to_collection():
    collection_id = request.form.get('collection_id')
    book_id = request.form.get('book_id')
    collection = Collection.query.get_or_404(collection_id)
    book = Book.query.get_or_404(book_id)

    if collection.user_id != current_user.id:
        abort(403)
    
    # Проверка, что книга не добавлена в коллекцию ранее
    existing_association = CollectionBookAssociation.query.filter_by(collection_id=collection_id, book_id=book_id).first()
    if not existing_association:
        association = CollectionBookAssociation(collection_id=collection.id, book_id=book.id)
        db.session.add(association)
        db.session.commit()
        flash(f'Книга успешно добавлена в подборку!', 'success')
    else:
        flash(f'Книга уже была добавлена в подборку!', 'primary')

    return redirect(url_for('book.show', book_id=book.id))

@bp.route('/delete_collection/<int:collection_id>', methods=['POST'])
@login_required
def delete_collection(collection_id):
    collection = Collection.query.get_or_404(collection_id)

    # Проверяем, что текущий пользователь имеет доступ к удалению коллекции
    if collection.user_id != current_user.id:
        abort(403)

    try:
        # Удаляем все ассоциации книг с этой коллекцией
        CollectionBookAssociation.query.filter_by(collection_id=collection_id).delete()
        
        # Удаляем саму коллекцию
        db.session.delete(collection)
        db.session.commit()

        flash(f'Подборка успешно удалена!', 'success')
    except Exception as e:
        flash(f'Ошибка при удалении подборки: {str(e)}', 'danger')
        db.session.rollback()

    return redirect(url_for('collection.my_collections'))

app/templates/collections/collections.html
<!-- templates/collections/collections.html -->
{% extends "base.html" %}

{% block content %}
<br><br>
<div class="container">
    <h1>Мои подборки</h1>
    <table class="table border">
        <thead>
            <tr>
                <th>Название</th>
                <th>Количество книг</th>
                <th>Дейстрвие</th>
            </tr>
        </thead>
        <tbody>
            {% for collection in collections %}
            <tr>
                <td>{{ collection.name }}</td>
                <td>{{ collection.books|length }}</td>
                <td>
				        <form action="{{ url_for('collection.delete_collection', collection_id=collection.id) }}" method="post" onsubmit="return confirm('Вы уверены, что хотите удалить эту подборку?');" style="display: inline;">
				        	<a href="{{ url_for('collection.view_collection', collection_id=collection.id) }}" class="btn btn-primary">Посмотреть</a>
				            <input type="hidden" name="_method" value="DELETE">
				            <button type="submit" class="btn btn-danger">Удалить подборку</button>
				        </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-success" data-toggle="modal" data-target="#addCollectionModal">Добавить подборку</button>
</div>

<!-- Add Collection Modal -->
<div class="modal fade" id="addCollectionModal" tabindex="-1" role="dialog" aria-labelledby="addCollectionModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCollectionModalLabel">Новая подборка</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ url_for('collection.add_collection') }}">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="collection-name">Название подборки</label>
                        <input type="text" class="form-control" id="collection-name" name="name" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/collections/view_collection.html
<!-- templates/collections/view_collection.html -->
{% extends "base.html" %}

{% block content %}
<br><br>

<div class="container">
    <h1>Подборка: {{ collection.name }}</h1>
    <br>
    <ul class="list-group">
        {% for book in books %}
        <li class="list-group-item">

            <a href="{{ url_for('book.show', book_id=book.book_id) }}">{{ book.book.title }}</a>
        </li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('collection.my_collections') }}" class="btn btn-secondary mt-3">Назад к подборкам</a>
</div>


{% endblock %}