app/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
import functools
from models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')

def check_rights(action):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            user = load_user(kwargs.get('user_id'))
            if current_user.is_anonymous:
                flash('Авторизуйтесь для просмотра данной страницы!', 'danger')
                return redirect(url_for('auth.login'))
            if not current_user.can(action):
                flash('У вас недостаточно прав для доступа к данной странице.', 'danger')
                return redirect(url_for('index'))
            return func(*args, **kwargs)
        return wrapper
    return decorator

def init_login_manager(app):
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'Для доступа к данной странице необходимо пройти процедуру аутентификации.'
    login_manager.login_message_category = 'warning'
    login_manager.user_loader(load_user)
    login_manager.init_app(app)

def load_user(user_id):
    user = User.query.get(user_id)
    return user

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login = request.form.get('login')
        password = request.form.get('password')
        if login and password:
            user = User.query.filter_by(login=login).first()
            if user and user.password_hash == password:
                login_user(user)
                flash('Вы успешно аутентифицированы.', 'success')
                next = request.args.get('next')
                return redirect(next or url_for('index'))
        flash('Невозможно аутентифицироваться с указанными логином и паролем', 'danger')
    return render_template('auth/login.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

app/templates/base.html
<!doctype html>
<html lang="ru" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>

    <title>Онлайн Библиотека "Литературный Оазис"</title>
</head>

<body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-lg bg-dark">
            <div class="container-fluid">
                <a class="btn navbar-brand btn-lg text-white" href="{{ url_for('index') }}">На главную</a>
                {% if current_user.is_authenticated %}
                <a class="btn navbar-brand btn-lg text-white" href="{{ url_for('reviews') }}">Мои рецензии</a>
                <a class="btn navbar-brand btn-lg text-white" href="{{ url_for('collection.my_collections') }}">Мои подборки</a>
                {% endif %}
                {% if current_user.is_authenticated %}
                <div class="col align-self-end mx-3">
                    <p class="text-white text-end">
                        {{ current_user.last_name }}
                        {{ current_user.first_name }}
                        {{ current_user.middle_name }}
                    </p>
                </div>
                <a class="btn text-white border-white p-3 nav-link btn-lg align-top" href="{{ url_for('auth.logout') }}">Выйти</a>
                {% else %}
                <a class="btn nav-link btn-lg text-white border-white p-3" href="{{ url_for('auth.login') }}">Войти</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <div class="alerts-area">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, msg in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show m-0 rounded-0" role="alert">
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endwith %}
    </div>

    <main class="main flex-grow-1 bg-light">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="mt-3 bg-dark d-flex align-items-center justify-content-center py-3">
        <p class="text-white">
            Гуламжанов Сулейман Улугбекович 221-351 ©
        </p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

    <script defer src="{{ url_for('static', filename='main.js') }}"></script>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}
{% from 'pagination.html' import pagination %}

{% block content %}
<br>
<h1 class="title my-3 font-weight-bold text-center">Онлайн-библиотека "Литературный Оазис"</h1>
<h2 class="title my-3 font-weight-bold text-center">Каталог книг:</h2>
<div class="container">
    {% if flag %}
    <div class="h-100 text-center d-flex p-3">
        <div class="m-auto">

            <table class="table border">
                <thead>
                    <tr>
                        <th scope="col">Обложка</th>
                        <th scope="col">Название</th>
                        <th scope="col">Жанр</th>
                        <th scope="col">Дата издания</th>
                        <th scope="col">Средняя оценка</th>
                        <th scope="col">Количество рецензий</th>
                        <th scope="col">Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                    <tr>
                        <th class="book-img">
                            <div class="course-logo"
                                style="background-image: url({{ book.get_img() }}); height: 200px;">
                            </div>
                        </th>
                        <th class="book-title">{{ book.title }}</th>
                        <th>
                            {% for genre in book_genre %}
                            {% if genre.books_id == book.id %}{{ genre.genre.genre_name }}</br>{% endif %}
                            {% endfor %}
                        </th>
                        <th>{{ book.year }}</th>
                        <th>{{ book.rating }}</th>
                        <th>{{ book.reviews|length }}</th>
                        <td>
                            <div class="btn-group">
                                <a class="btn btn-primary"
                                    href="{{ url_for('book.show', book_id=book.id) }}">Просмотр</a>
                                {% if current_user.is_authenticated %}
                                {% if current_user.can('edit') %}
                                <a class="btn btn-secondary"
                                    href="{{ url_for('book.edit', book_id=book.id) }}">Редактирование</a>
                                {% endif %}
                                {% if current_user.can('delete') %}
                                <button type="button" class="btn btn-danger"
                                    data-url="{{ url_for('book.delete', book_id=book.id) }}" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal" data-title="{{ book.title }}">
                                    Удалить
                                </button>
                                {% endif %}
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="mb-5">
                {{ pagination(page, page_count, request.endpoint) }}
            </div>
        </div>
    </div>
    {% endif %}
    {% if not flag %}
    <h3 class="title my-3 font-weight-bold text-center">Ничего не найдено</h3>
    {% endif %}
    {% if current_user.is_authenticated and current_user.can('delete') %}
    <div class="text-center my-3">
        <a class="btn btn-lg btn-primary" href="{{ url_for('book.new') }}">Добавить новую книгу</a>
    </div>
    {% endif %}
</div>

{% if current_user.is_authenticated %}
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Удаление книги</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Вы уверены, что хотите удалить книгу
                "<span class="delete-title"></span>"
                ?
                <form action="" class="d-none" method="POST">
                    <input type="submit" id="submit-delete">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <label for="submit-delete" class="btn btn-danger mb-0">Удалить</label>
            </div>
        </div>
    </div>
</div>
{%endif%}

<script src="{{ url_for('static', filename='delete.js')}}"></script>
{% endblock %}

app/templates/pagination.html
{% macro pagination(page, page_count, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item {% if page == 1 %} disabled {% endif %}"><a class="page-link" href="{{ url_for(endpoint, page=page-1) }}">Previous</a></li>
      {%set start = 1 if page <= 3 else page - 3%}
      {%set end = page_count if page + 3 > page_count else page + 3%}

      {% for i in range(start, end + 1) %}
      <li class="page-item {% if i == page %} active {% endif %}"><a class="page-link" href="{{ url_for(endpoint, page=i) }}">{{i}}</a></li>
      {% endfor%}
      
      <li class="page-item {% if page == page_count %} disabled {% endif %}"><a class="page-link" href="{{ url_for(endpoint, page=page+1) }}">Next</a></li>
    </ul>
</nav>
{% endmacro %}